/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Retrieve */

#ifndef _Included_Retrieve
#define _Included_Retrieve
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Retrieve
 * Method:    retrieve
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Retrieve_retrieve
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
